#!/bin/bash

#SBATCH -p short              # partition name
#SBATCH -c 2                  # number of cores
#SBATCH -t 0-2:00             # time limit
#SBATCH --mem 8G              # requested memory
#SBATCH --job-name alignment  # job name
#SBATCH -o %j.out	      # file to which standard output will be written
#SBATCH -e %j.err 	      # file to which standard error will be written

module load gcc/6.2.0 bowtie2/2.2.9 samtools/1.13

bowtie2 -p 2 -q --local \
-x /n/groups/shared_databases/bowtie2_indexes/mm10 \
-U ~/chipseq_workshop/raw_data/wt_sample2_chip.fastq.gz \
-S ~/chipseq_workshop/results/bowtie2/wt_sample2_chip.sam

samtools view -h -S -b \
-o ~/chipseq_workshop/results/bowtie2/wt_sample2_chip.bam \
~/chipseq_workshop/results/bowtie2/wt_sample2_chip.sam

rm ~/chipseq_workshop/results/bowtie2/wt_sample2_chip.sam
