#!/bin/bash
#SBATCH --partition=jumbo_long       # the requested queue
#SBATCH --nodes=1              # number of nodes to use
#SBATCH --tasks-per-node=1     #
#SBATCH --cpus-per-task=8      #   
#SBATCH --mem-per-cpu=4G     # in megabytes, unless unit explicitly stated
#SBATCH --error=logs/%J.err         # redirect stderr to this file
#SBATCH --output=logs/%J.out        # redirect stdout to this file
#SBATCH --mail-user=wilsoncl6@cardiff.ac.uk  # email
#SBATCH --mail-type=BEGIN,END,FAIL      # email on job start, end, and/or failure


## Load some modules
module load  STAR/2.7.6a


## Point to directory containing the reference genome where your sequences will map
export refdir=/mnt/scratch45/c21010903/jumble

## Declare your working directory
export workingdir=/mnt/scratch45/c21010903 


## The commands you want to run

# Index your reference genome so that it can be quickly accessed by STAR
STAR    --runThreadN ${SLURM_CPUS_PER_TASK} \
        --limitGenomeGenerateRAM 31000000000 \
        --runMode genomeGenerate \
        --genomeDir  $refdir/ \
        --genomeFastaFiles $refdir/Ri_AB.fasta \
        --sjdbGTFfile $refdir/Ri_AB.gff3 \
        --sjdbGTFfeatureExon exon \
        --sjdbGTFtagExonParentTranscript Parent \
        --sjdbOverhang 129 \
        --genomeSAindexNbases 13

# Note: Change --sjdbOverhang to length of your sequence data minus 1

# List of sequences to align
list=("HT-64" "HT-63" "HT-62" "WA-61" "WA-60" "WA-59")

# Create a new directory to store alignment files
mkdir star

# Map forward and reverse reads to indexed genome

for i in ${list[@]}

#do
        echo ${i}

        STAR   --outMultimapperOrder Random \
        --outSAMmultNmax 1 \
        --runThreadN ${SLURM_CPUS_PER_TASK}  \
        --runMode alignReads \
        --outSAMtype BAM Unsorted \
        --quantMode GeneCounts \
        --outFileNamePrefix $workingdir/star/${i}_unsort. \
        --genomeDir $refdir \
        --readFilesIn $workingdir/trimmed_reads/${i}_fp1.fastq.gz $workingdir/trimmed_reads/${i}_fp2.fastq.gz \
        --readFilesCommand zcat

done
